"""Crop library seed data. Run: python -m seeds.crops"""
from app.database import SessionLocal
from app.models.crop import Crop

CROPS = [
    Crop(
        id="lettuce",
        name="Lettuce",
        category="Leafy Green",
        icon="\U0001f96c",
        accent="#9edb66",
        weeks_on_panel=5,
        nursery_lead_weeks=2,
        yield_per_grid=1.2,
        price_per_kg=4.0,
        seedlings_per_grid=80,
        tray_cell_count=200,
        germination_rate=0.95,
        prefers_edge=True,
        edge_weight=1.1,
        neighbor_bonus=2.0,
        nutrient_cost_per_grid_week=0.10,
        cost_per_seedling=0.02,
    ),
    Crop(
        id="basil",
        name="Basil",
        category="Herb",
        icon="\U0001f33f",
        accent="#86c56a",
        weeks_on_panel=6,
        nursery_lead_weeks=2,
        yield_per_grid=0.6,
        price_per_kg=12.0,
        seedlings_per_grid=100,
        tray_cell_count=200,
        germination_rate=0.90,
        prefers_edge=False,
        edge_weight=0.9,
        neighbor_bonus=2.8,
        nutrient_cost_per_grid_week=0.12,
        cost_per_seedling=0.03,
    ),
    Crop(
        id="kale",
        name="Kale",
        category="Leafy Green",
        icon="\U0001f957",
        accent="#64b95d",
        weeks_on_panel=7,
        nursery_lead_weeks=2,
        yield_per_grid=1.4,
        price_per_kg=6.0,
        seedlings_per_grid=80,
        tray_cell_count=200,
        germination_rate=0.92,
        prefers_edge=True,
        edge_weight=1.25,
        neighbor_bonus=2.2,
        nutrient_cost_per_grid_week=0.10,
        cost_per_seedling=0.02,
    ),
    Crop(
        id="mint",
        name="Mint",
        category="Herb",
        icon="\U0001f331",
        accent="#73d0a8",
        weeks_on_panel=8,
        nursery_lead_weeks=2,
        yield_per_grid=0.5,
        price_per_kg=8.0,
        seedlings_per_grid=100,
        tray_cell_count=200,
        germination_rate=0.88,
        prefers_edge=False,
        edge_weight=0.0,
        neighbor_bonus=3.2,
        nutrient_cost_per_grid_week=0.08,
        cost_per_seedling=0.02,
    ),
    Crop(
        id="cilantro",
        name="Cilantro",
        category="Herb",
        icon="\U0001f33f",
        accent="#7ec88b",
        weeks_on_panel=4,
        nursery_lead_weeks=2,
        yield_per_grid=0.4,
        price_per_kg=10.0,
        seedlings_per_grid=120,
        tray_cell_count=200,
        germination_rate=0.85,
        prefers_edge=False,
        edge_weight=0.8,
        neighbor_bonus=2.5,
        nutrient_cost_per_grid_week=0.10,
        cost_per_seedling=0.025,
    ),
    Crop(
        id="arugula",
        name="Arugula",
        category="Leafy Green",
        icon="\U0001f96c",
        accent="#a3c44a",
        weeks_on_panel=4,
        nursery_lead_weeks=1,
        yield_per_grid=0.8,
        price_per_kg=9.0,
        seedlings_per_grid=100,
        tray_cell_count=200,
        germination_rate=0.90,
        prefers_edge=True,
        edge_weight=1.0,
        neighbor_bonus=2.0,
        nutrient_cost_per_grid_week=0.10,
        cost_per_seedling=0.02,
    ),
    Crop(
        id="spinach",
        name="Spinach",
        category="Leafy Green",
        icon="\U0001f96c",
        accent="#5ba84e",
        weeks_on_panel=5,
        nursery_lead_weeks=2,
        yield_per_grid=1.0,
        price_per_kg=5.0,
        seedlings_per_grid=80,
        tray_cell_count=200,
        germination_rate=0.88,
        prefers_edge=True,
        edge_weight=1.15,
        neighbor_bonus=2.0,
        nutrient_cost_per_grid_week=0.10,
        cost_per_seedling=0.02,
    ),
    Crop(
        id="chard",
        name="Swiss Chard",
        category="Leafy Green",
        icon="\U0001f96c",
        accent="#d4594e",
        weeks_on_panel=6,
        nursery_lead_weeks=2,
        yield_per_grid=1.3,
        price_per_kg=5.5,
        seedlings_per_grid=70,
        tray_cell_count=200,
        germination_rate=0.90,
        prefers_edge=True,
        edge_weight=1.0,
        neighbor_bonus=1.8,
        nutrient_cost_per_grid_week=0.10,
        cost_per_seedling=0.02,
    ),
]


def seed_crops() -> None:
    db = SessionLocal()
    try:
        for crop in CROPS:
            existing = db.get(Crop, crop.id)
            if not existing:
                db.add(crop)
        db.commit()
        print(f"Seeded {len(CROPS)} crops")
    finally:
        db.close()


if __name__ == "__main__":
    seed_crops()
